[package]
name = "silicate"
version = "0.4.0"
edition = "2024"
authors = ["An Tran <antran@caltech.edu>"]
description = "Cross-platform GPU-accelerated Procreate file viewer.s"
readme = "README.md"
repository = "https://github.com/Avarel/procreate-rs"
license = "MIT"

[workspace]
members = ["libs/compositor", "libs/silica", "libs/silica-gpu"]

[workspace.dependencies]
wgpu = "27.0"

[features]
default = []

[dependencies]
log = "0.4"

silicate-compositor = { path = "libs/compositor" }
silica-gpu = { path = "libs/silica-gpu" }

image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "tga",
    "tiff",
    "webp",
    "bmp",
] }

# Display GUI
egui = "0.33"
eframe = { version = "0.33", default-features = false, features = [
    "default_fonts",
    "persistence",
    "wgpu",
    "wayland",
    "x11",
] }
egui_dock = "0.18"
egui-notify = "0.21"

serde = { version = "1.0", features = ["derive"] }

rfd = { version = "0.17", default-features = false, features = ["xdg-portal"] }
# Async runtime

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["sync", "rt-multi-thread"] }
env_logger = "0.11.8"
memmap2 = "0.9"
clap = { version = "4.5", features = ["cargo", "derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", features = ["sync", "rt"] }
wasm-bindgen-futures = "0.4.64"
web-sys = { version = "0.3.91", features = ["RequestInit", "RequestMode", "Request", "Headers", "Response"]}

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1

[build-dependencies]
winres = "0.1"
cc = "1.2"

[package.metadata.bundle]
name = "Silicate"
identifier = "io.antran.silicate"
icon = ["assets/favicon.ico"]
category = "Utility"
