[package]
name = "procreate-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6"
minilzo-rs = "0.6.0"
plist = "1.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
regex = "1.6"
image = "0.24"
rayon = "1.5"
once_cell = "1"
wgpu = "0.13"
futures = "0.3"
bytemuck = { version = "1.12", features = ["derive"] }
memmap2 = "0.5"
# Display GUI
egui = { version = "0.19", features = ["bytemuck"] }
egui-wgpu = "0.19"
egui-winit = "0.19"
winit = "0.27"
parking_lot = "0.12"