[package]
name = "silicate"
version = "0.3.0"
edition = "2021"
authors = ["An Tran <antran@caltech.edu>"]
description = "Cross-platform GPU-accelerated Procreate file viewer.s"
readme = "README.md"
repository = "https://github.com/Avarel/procreate-rs"
license = "MIT"

[workspace]
members = ["libs/compositor", "libs/silica", "libs/silica-gpu"]

[workspace.dependencies]
wgpu = "27.0"

[features]
default = []

[dependencies]
silicate-compositor = { path = "libs/compositor" }
silica-gpu = { path = "libs/silica-gpu" }

clap = { version = "4.5", features = ["cargo", "derive"] }

image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "tga",
    "tiff",
    "webp",
    "bmp",
] }
# Display GUI
egui = "0.33"
egui-wgpu = "0.33"
egui-winit = "0.33"
# winit = "0.29"
egui_dock = "0.18"
egui-notify = "0.21"

rfd = { version = "0.17", default-features = false, features = ["xdg-portal"] }
# Async runtime
tokio = { version = "1.48", features = ["sync", "rt-multi-thread"] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[build-dependencies]
cc = "1.2"

[package.metadata.bundle]
name = "Silicate"
identifier = "io.antran.silicate"
icon = ["assets/icon.ico"]
category = "Utility"
