[package]
name = "procreate-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "libs/egui_dock"
]

[dependencies]
zip = "0.6"
minilzo-rs = "0.6.0"
plist = "1.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
regex = "1.6"
image = { version = "0.24", features = ["png", "jpeg", "tga", "tiff", "webp", "bmp", "jpeg_rayon"]}
rayon = "1.5"
once_cell = "1"
wgpu = "0.13"
bytemuck = { version = "1.12", features = ["derive"] }
memmap2 = "0.5"
parking_lot = "0.12"
# Display GUI
egui = "0.19"
egui-wgpu = "0.19"
egui-winit = "0.19"
winit = "0.27"
# egui_dock = "0.2"
egui_dock = { path = "libs/egui_dock" }
egui-notify = "0.4.0"
# Async runtime
rfd = { version = "0.10", default-features = false, features = ["xdg-portal"] }
tokio = { version = "1.21", features = ["sync", "rt", "rt-multi-thread", "time"] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
