[package]
name = "silica-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"

wgpu = { workspace = true }
silica = { path = "../silica" }

# Procreate support
zip = { version = "8.2", default-features = false, features = ["deflate"] }
lzokay = { version = "2.0", default-features = false, features = [
    "decompress",
] }
lz4_flex = { version = "0.12", default-features = false, features = ["frame"] }
rayon = "1"
